name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd node-js && npm ci
      - run: cd node-js && npm run build --if-present
      - run: cd node-js && npm run cover
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
